<?php

namespace AppBundle\Repository;

/**
 * SubjectOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
