app_index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  GET

subject:
    type:     rest
    resource: AppBundle\Controller\SubjectController
    prefix: /api

vote:
    type:     rest
    resource: AppBundle\Controller\VoteController
    prefix: /api

api_login_check:
    path: /api/login_check

registration:
    type: rest
    resource: AppBundle\Controller\RegistrationController
    prefix: /api
